---
title: "STATS 401 (Winter 2018) <br>'Applied Statistical Methods II'"
author: "Instructor: Edward L. Ionides"
output:
  html_document:
    theme: flatly
    toc: yes
csl: ecology.csl
---

------

## Course description

* An intermediate course in applied statistics, covering a range of topics in modeling and analysis of data including: review of simple linear regression, two-sample problems, one-way analysis of variance; multiple linear regression, diagnostics and model selection; two-way analysis of variance, multiple comparisons, and other selected topics. (4 Credits)

* Advisory Pre-requisites: MATH 115 and one of (STATS 180 or STATS 250 or STATS 280, STATS 412 or ECON 451). No credit granted if completed or enrolled in STATS 413.

* We will build on material in STATS 250. Notes and labs for 250 are [available online](https://open.umich.edu/find/open-educational-resources/statistics/statistics-250-introduction-statistics-data-analysis).
STATS 280, STATS 412 and ECON 451 are more advanced and therefore entirely adequate preparation. STATS 180 is a sufficient background but will require some extra catch-up.

--------------

## Course information

* Class meets Monday/Wednesday 1:00-2:30 in 1360 East Hall
* Contact information:
    + Office: 453 West Hall 
    + Phone: 647 5457 
    + E-mail: ionides@umich.edu 
    + Web: dept.stat.lsa.umich.edu/~ionides
    + Office hours:  TBA
* Final exam: Tuesday April 24, 4:00-6:00pm
* Instructor office hours: Monday 4-5pm, Wednesday 3-4pm
* Labs, in B760 East Hall
    + Section 401-003. Thu 7-8:30pm. GSI: Yuan Sun (yuansun@umich.edu)
    + Section 401-004. Thu 11:30am-1:00pm. GSI: Sanjana Gupta (gsan@umich.edu)
    + Section 401-005. Fri 1-2:30. GSI: Naomi Giertych (ngierty@umich.edu)
* GSI office hours, 2165 USB, the Science Learning Center Annex
    + Yuan Sun. Mon 9-11 am 
    + Sanjana Gupta. Tue 9-11 am
    + Naomi Giertych. Thu 9-11 am
    + You may prefer to visit your Section GSI, but you're welcome to go to any office hours
* Open office hours. You are also welcome to ask STATS 401 questions to any available Statistics GSI at USB during the open hours: Mon 9-11 am & 1-10 pm; Tue to Thu 9 am – 10 pm;  Friday 9–11 am & 1–4 pm;  Sat CLOSED; Sunday 12 pm – 10 pm.
* Computing support: inquire by email, with a detailed description of the problem, what you did, and any error message you obtained. It can be helpful to provide a minimal example that can be run to demonstrate the problem. Please email your Section GSI.
* Textbook: S. Sheather ``A Modern Approach to Regression with R''. A pdf is available from the UM Library.

-----------

##  Grading

* Weekly homeworks (20\%) due at the start of lab. Extensions will be granted upon request for up to two late homeworks. Subsequent late homeworks will receive no credit.
* Two lab quizzes (5\%+5\%) in lab on February 1 or 2, and March 29 or 30.
* Midterm exam (20\%) in class on Wednesday 2/21).
* Final exam (50\%) on Tuesday, April 24, 4:00pm - 6:00pm

Homework will be graded on completeness. 
To get these points, the homework must include two statements titled "Sources" and "Please explain".
 
* The statement of sources must list all books, internet resources or other people consulted while completing the homework. For example, "Sources: notes only," or, "Sources: collaboration with X and Y; web site Z," or, "Sources: notes and office hours."
Any material taken from any source, such as the internet, must be properly acknowledged. 
Directly copied text must be in quotation marks.
Directly copied equations must be explicitly referenced to the source.
Unattributed copying from any source is plagiarism, and has potentially [serious consequences](https://lsa.umich.edu/lsa/academics/academic-integrity/academic-misconduct.html).

* The explanation request provides useful feedback for the GSI and instructor. For example, "Please explain: nothing, everything is clear," or, "Please explain: I'm confused by summation notation. What is $\sum_{i=1}^n j$?'' or, "Please explain: I wanted to add a label to a point on a graph. How do you do that in R?"

Homework will not be graded on correctness, to encourage independent work.
The GSI may provide some feedback on correctness, but students are responsible for checking their work against posted solutions.


----------

## Class notes

1. [Introduction](01/notes01.pdf). [(R script)](01/notes01.R).

2. [Linear algebra for applied statistics](02/notes02.pdf). [(R script)](02/notes02.R).

3. [Fitting a linear model to a sample by least squares](03/notes03.pdf). [(R script)](03/notes03.R).

4. [Toward a population version of the linear model](04/notes04.pdf).
[Random variables (from 401W17)](04/401f17-chapter2.pdf).
[Bivariate random variables (from 401W17)](04/401f17-chapter3.pdf).
 
5. [Vector random variables](05/notes05.pdf). [(R script)](05/notes05.R).

5. [Hypothesis testing and confidence intervals](06/notes06.pdf). 
[Topics in comparing means of one or two samples](06/testing_means.pdf).
[Reading Sheather and other texts](06/texts.html).

--------

## Homework assignments

* [Homework 0. Setting up your laptop](hw/hw00/hw00.html). 
Due in class on 1/3.

* [Homework 1. Introduction to R](hw/hw01/hw01.html). 
Due in your lab on 1/11 or 1/12. [Solutions, as a text file of R commands](hw/hw01/sol_hw01.R).

* [Homework 2. More swirl and matrix exercises](hw/hw02/hw02.html). 
Due in your lab on 1/18 or 1/19. [Solutions, as a pdf file](hw/hw02/Hw2_Solutions.pdf) or [R script](hw/hw02/Hw2_Solutions.Rmd)

* [Homework 3. More swirl and fitting a linear model via matrix computations](hw/hw03/hw03.html). 
Due in your lab on 1/25 or 1/26. [Solutions](hw/hw03/sol_hw03.html).

* [Homework 4. Summation exercises and a historic data analysis](hw/hw04/hw04.html). 
Due in your lab on 2/1 or 2/2. [Solutions](hw/hw04/sol_hw04.html).

* [Homework 5. Probability exercises and an application to a randomized experiment](hw/hw05/hw05.html). 
Due in your lab on 2/8 or 2/9. [Solutions](hw/hw05/sol_hw05.html).

* [Homework 6. Variance, covariance and standard errors for fitting a linear model](hw/hw06/hw06.html). 
Due in your lab on 2/15 or 2/16.

------------

## Lab materials

* [Lab 1. Introduction to R](lab/lab01/lab01.pdf). Slides for 1/4 and 1/5.

* [Lab 2. Practicing matrix operations](lab/lab02/lab02.pdf). Slides for 1/11 and 1/12.

* [Lab 3. Using matrices for fitting a linear model by least squares ](lab/lab03/lab03.pdf). Slides for 1/18 and 1/19. [Solutions](lab/lab03/sol_lab03.pdf).

* [Lab 4. Summation and quiz review](lab/lab04/lab04.pdf). Slides for 1/25 and 1/26. [Sample quiz](lab/lab04/sample_quiz.pdf). 

* Lab 5. Quiz.

* [Lab 6. Variance, covariance and standard errors for the linear model](lab/lab06/lab06.pdf). Slides for 2/8 and 2/9.

<!--
[Solutions](lab/lab04/sol_lab04.pdf)
-->

------------

## Quiz materials

* [Information and practice for quiz 1](quiz1/quiz1.html).
 Also provided is a [list of all the questions in the quiz generator](quiz1/quiz1-all.html).

## Midterm exam materials

* [Information and outline for the midterm](mt/info.html).

* [Practice midterm exam](mt/practice-mt.html).

------------

-----------

