---
title: "Homework 9, STATS 401 W18"
author: "Due in your lab on 4/12 or 4/13"
output:
  html_document:
    theme: flatly
    toc: yes
csl: ecology.csl
---

\newcommand\E{\mathrm{E}}
\newcommand\SE{\mathrm{SE}}
\newcommand\var{\mathrm{Var}}
\newcommand\cov{\mathrm{Cov}}
\newcommand\prob{\mathrm{P}}
\newcommand\mat[1]{\mathbb{#1}}
\renewcommand\vect[1]{\boldsymbol{\mathrm{#1}}}
\newcommand\transpose{{\scriptscriptstyle \mathrm{T}}}
\usepackage{amsmath}


**Write a report analyzin the following dataset. Include R code as an appendix.
Recall that you are permitted to collaborate, or to use any internet resources, but you must list all sources that make a substantial contribution to your report.
As usual, following the syllabus, you are also requested to give some feedback in a "Please explain" statement.
**

**This capstone homework will be graded on completeness, as for other homeworks. In this case, completeness will be measured by how many of the ideas we have developed in the course you consider in your report. The capstone homework will count as two homeworks for the purpose of assigning credit.**

Data on 12 variables for 113 hospitals from the Study on the Efficacy of Nosocomial Infection Control (SENIC) are provided in the file [senic.txt](senic.txt). 
The primary purpose of this study is to look for properties of hospitals associated with high (or low) rates of hospital-acquired infections, which have the technical name of *nosocomial infections*.
The rate of nosocomial infections is measured by the variable `Infection risk`.
The SENIC study was described in a sequence of articles in The American Journal of Epidemiology, Volume 111, Issue 5, 1980, Pages 465–653. 
You are not expected to read these articles.
Nosocomial infection continues to be a concern for hospital management, and SENIC was a landmark study on this topic. 
The variables are described as follows:

**Hospital**: index from 1 to 113

**Length of stay**: average duration (in days) for all patients

**Age**: average age (in years) for all patients

**Infection risk**: estimated percentage of patients acquiring an infection in hospital

**Culture**: average number of cultures for each patient without signs or symptoms of hospital-acquired infection, times 100

**X-ray**: number of X-ray procedures divided by number of patients without signs or symptoms of pneumonia, times 100

**Beds**: average number of beds in the hospital

**Med school**: does the hospital have an affiliated medical school (1=Yes;2=No)

**Region**: geographic region (1=North-East, 2=North-Central, 3=South, 4=West)

**Patients**: average daily census of number of patients in the hospital

**Nurses**: average number of full-time equivalent registed and licensed nurses

**Facilities**: percent of 35 specific facilities and services which are provided by the hospital

Explore these data to find statistically supported evidence of associations that might explain nosocomial infection risk.
You are expected to use the linear modeling techniques we have learned in class, as well as making one or more appropriate graphs.
You may try as many different models as you like, but focus your report on a subset of analyses that you find informative.
Numerical analysis that you present should be combined with explanation of your methods and conclusions.


--------------

-------------

License: This material is provided under an [MIT license](https://ionides.github.io/401w18/LICENSE)<br>


------
